# 出现的错误
```
  Failed start 10 of 18 segment instances
```
[gpadmin@GP_Master ~]$ gpstart -a
20190329:17:56:26:002834 gpstart:GP_Master:gpadmin-[INFO]:-Starting gpstart with args: -a
20190329:17:56:26:002834 gpstart:GP_Master:gpadmin-[INFO]:-Gathering information and validating the environment...
20190329:17:56:26:002834 gpstart:GP_Master:gpadmin-[INFO]:-Greenplum Binary Version: 'postgres (Greenplum Database) 5.16.0 build commit:23cec7df0406d69d6552a4bbb77035dba4d7dd44'
20190329:17:56:26:002834 gpstart:GP_Master:gpadmin-[INFO]:-Greenplum Catalog Version: '301705051'
20190329:17:56:26:002834 gpstart:GP_Master:gpadmin-[INFO]:-Starting Master instance in admin mode
20190329:17:56:27:002834 gpstart:GP_Master:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20190329:17:56:27:002834 gpstart:GP_Master:gpadmin-[INFO]:-Obtaining Segment details from master...
20190329:17:56:27:002834 gpstart:GP_Master:gpadmin-[INFO]:-Setting new master era
20190329:17:56:27:002834 gpstart:GP_Master:gpadmin-[INFO]:-Master Started...
20190329:17:56:27:002834 gpstart:GP_Master:gpadmin-[INFO]:-Shutting down master
20190329:17:56:29:002834 gpstart:GP_Master:gpadmin-[INFO]:-Commencing parallel segment instance startup, please wait...
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-Process results...
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[ERROR]:-No segment started for content: 1.
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-dumping success segments: ['GP_Segment_1:/opt/greenplum/data/primary/gpseg2:content=2:dbid=4:mode=s:status=u', 'GP_Segment_1:/opt/greenplum/data2/primary/gpseg4:content=4:dbid=6:mode=s:status=u', 'GP_Segment_1:/opt/greenplum/data2/primary/gpseg5:content=5:dbid=7:mode=s:status=u', 'GP_Segment_1:/opt/greenplum/data/primary/gpseg0:content=0:dbid=2:mode=s:status=u', 'GP_Segment_2:/opt/greenplum/data/primary/gpseg7:content=7:dbid=9:mode=s:status=u', 'GP_Segment_2:/opt/greenplum/data/primary/gpseg6:content=6:dbid=8:mode=s:status=u', 'GP_Segment_2:/opt/greenplum/data2/primary/gpseg10:content=10:dbid=12:mode=s:status=u', 'GP_Segment_2:/opt/greenplum/data2/primary/gpseg11:content=11:dbid=13:mode=s:status=u']
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-----------------------------------------------------
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-DBID:14  FAILED  host:'GP_Segment_3' datadir:'/opt/greenplum/data/primary/gpseg12' with reason:'cmd had rc=2 completed=True halted=False
  stdout='20190329:17:56:29:002460 gpsegstart.py_GP_Segment_3:gpadmin:GP_Segment_3:gpadmin-[INFO]:-Starting gpsegstart.py with args: -C en_US.utf8:en_US.utf8:en_US.utf8 -M mirrorless -V postgres (Greenplum Database) 5.16.0 build commit:23cec7df0406d69d6552a4bbb77035dba4d7dd44 -n 18 --era f9981c2cfd29d865_190329175627 -t 600 --master-checksum-version 1 -D 14|12|p|p|s|u|GP_Segment_3|GP_Segment_3|6000|None|/opt/greenplum/data/primary/gpseg12|| -D 15|13|p|p|s|u|GP_Segment_3|GP_Segment_3|6001|None|/opt/greenplum/data/primary/gpseg13|| -D 16|14|p|p|s|u|GP_Segment_3|GP_Segment_3|6002|None|/opt/greenplum/data/primary/gpseg14|| -D 17|15|p|p|s|u|GP_Segment_3|GP_Segment_3|6003|None|/opt/greenplum/data2/primary/gpseg15|| -D 18|16|p|p|s|u|GP_Segment_3|GP_Segment_3|6004|None|/opt/greenplum/data2/primary/gpseg16|| -D 19|17|p|p|s|u|GP_Segment_3|GP_Segment_3|6005|None|/opt/greenplum/data2/primary/gpseg17|| -B 64
20190329:17:56:29:002460 gpsegstart.py_GP_Segment_3:gpadmin:GP_Segment_3:gpadmin-[CRITICAL]:-gpsegstart.py failed. (Reason='[Errno 12] Cannot allocate memory') exiting...
'
  stderr='''
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-DBID:15  FAILED  host:'GP_Segment_3' datadir:'/opt/greenplum/data/primary/gpseg13' with reason:'cmd had rc=2 completed=True halted=False
  stdout='20190329:17:56:29:002460 gpsegstart.py_GP_Segment_3:gpadmin:GP_Segment_3:gpadmin-[INFO]:-Starting gpsegstart.py with args: -C en_US.utf8:en_US.utf8:en_US.utf8 -M mirrorless -V postgres (Greenplum Database) 5.16.0 build commit:23cec7df0406d69d6552a4bbb77035dba4d7dd44 -n 18 --era f9981c2cfd29d865_190329175627 -t 600 --master-checksum-version 1 -D 14|12|p|p|s|u|GP_Segment_3|GP_Segment_3|6000|None|/opt/greenplum/data/primary/gpseg12|| -D 15|13|p|p|s|u|GP_Segment_3|GP_Segment_3|6001|None|/opt/greenplum/data/primary/gpseg13|| -D 16|14|p|p|s|u|GP_Segment_3|GP_Segment_3|6002|None|/opt/greenplum/data/primary/gpseg14|| -D 17|15|p|p|s|u|GP_Segment_3|GP_Segment_3|6003|None|/opt/greenplum/data2/primary/gpseg15|| -D 18|16|p|p|s|u|GP_Segment_3|GP_Segment_3|6004|None|/opt/greenplum/data2/primary/gpseg16|| -D 19|17|p|p|s|u|GP_Segment_3|GP_Segment_3|6005|None|/opt/greenplum/data2/primary/gpseg17|| -B 64
20190329:17:56:29:002460 gpsegstart.py_GP_Segment_3:gpadmin:GP_Segment_3:gpadmin-[CRITICAL]:-gpsegstart.py failed. (Reason='[Errno 12] Cannot allocate memory') exiting...
'
  stderr='''
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-DBID:16  FAILED  host:'GP_Segment_3' datadir:'/opt/greenplum/data/primary/gpseg14' with reason:'cmd had rc=2 completed=True halted=False
  stdout='20190329:17:56:29:002460 gpsegstart.py_GP_Segment_3:gpadmin:GP_Segment_3:gpadmin-[INFO]:-Starting gpsegstart.py with args: -C en_US.utf8:en_US.utf8:en_US.utf8 -M mirrorless -V postgres (Greenplum Database) 5.16.0 build commit:23cec7df0406d69d6552a4bbb77035dba4d7dd44 -n 18 --era f9981c2cfd29d865_190329175627 -t 600 --master-checksum-version 1 -D 14|12|p|p|s|u|GP_Segment_3|GP_Segment_3|6000|None|/opt/greenplum/data/primary/gpseg12|| -D 15|13|p|p|s|u|GP_Segment_3|GP_Segment_3|6001|None|/opt/greenplum/data/primary/gpseg13|| -D 16|14|p|p|s|u|GP_Segment_3|GP_Segment_3|6002|None|/opt/greenplum/data/primary/gpseg14|| -D 17|15|p|p|s|u|GP_Segment_3|GP_Segment_3|6003|None|/opt/greenplum/data2/primary/gpseg15|| -D 18|16|p|p|s|u|GP_Segment_3|GP_Segment_3|6004|None|/opt/greenplum/data2/primary/gpseg16|| -D 19|17|p|p|s|u|GP_Segment_3|GP_Segment_3|6005|None|/opt/greenplum/data2/primary/gpseg17|| -B 64
20190329:17:56:29:002460 gpsegstart.py_GP_Segment_3:gpadmin:GP_Segment_3:gpadmin-[CRITICAL]:-gpsegstart.py failed. (Reason='[Errno 12] Cannot allocate memory') exiting...
'
  stderr='''
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-DBID:17  FAILED  host:'GP_Segment_3' datadir:'/opt/greenplum/data2/primary/gpseg15' with reason:'cmd had rc=2 completed=True halted=False
  stdout='20190329:17:56:29:002460 gpsegstart.py_GP_Segment_3:gpadmin:GP_Segment_3:gpadmin-[INFO]:-Starting gpsegstart.py with args: -C en_US.utf8:en_US.utf8:en_US.utf8 -M mirrorless -V postgres (Greenplum Database) 5.16.0 build commit:23cec7df0406d69d6552a4bbb77035dba4d7dd44 -n 18 --era f9981c2cfd29d865_190329175627 -t 600 --master-checksum-version 1 -D 14|12|p|p|s|u|GP_Segment_3|GP_Segment_3|6000|None|/opt/greenplum/data/primary/gpseg12|| -D 15|13|p|p|s|u|GP_Segment_3|GP_Segment_3|6001|None|/opt/greenplum/data/primary/gpseg13|| -D 16|14|p|p|s|u|GP_Segment_3|GP_Segment_3|6002|None|/opt/greenplum/data/primary/gpseg14|| -D 17|15|p|p|s|u|GP_Segment_3|GP_Segment_3|6003|None|/opt/greenplum/data2/primary/gpseg15|| -D 18|16|p|p|s|u|GP_Segment_3|GP_Segment_3|6004|None|/opt/greenplum/data2/primary/gpseg16|| -D 19|17|p|p|s|u|GP_Segment_3|GP_Segment_3|6005|None|/opt/greenplum/data2/primary/gpseg17|| -B 64
20190329:17:56:29:002460 gpsegstart.py_GP_Segment_3:gpadmin:GP_Segment_3:gpadmin-[CRITICAL]:-gpsegstart.py failed. (Reason='[Errno 12] Cannot allocate memory') exiting...
'
  stderr='''
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-DBID:18  FAILED  host:'GP_Segment_3' datadir:'/opt/greenplum/data2/primary/gpseg16' with reason:'cmd had rc=2 completed=True halted=False
  stdout='20190329:17:56:29:002460 gpsegstart.py_GP_Segment_3:gpadmin:GP_Segment_3:gpadmin-[INFO]:-Starting gpsegstart.py with args: -C en_US.utf8:en_US.utf8:en_US.utf8 -M mirrorless -V postgres (Greenplum Database) 5.16.0 build commit:23cec7df0406d69d6552a4bbb77035dba4d7dd44 -n 18 --era f9981c2cfd29d865_190329175627 -t 600 --master-checksum-version 1 -D 14|12|p|p|s|u|GP_Segment_3|GP_Segment_3|6000|None|/opt/greenplum/data/primary/gpseg12|| -D 15|13|p|p|s|u|GP_Segment_3|GP_Segment_3|6001|None|/opt/greenplum/data/primary/gpseg13|| -D 16|14|p|p|s|u|GP_Segment_3|GP_Segment_3|6002|None|/opt/greenplum/data/primary/gpseg14|| -D 17|15|p|p|s|u|GP_Segment_3|GP_Segment_3|6003|None|/opt/greenplum/data2/primary/gpseg15|| -D 18|16|p|p|s|u|GP_Segment_3|GP_Segment_3|6004|None|/opt/greenplum/data2/primary/gpseg16|| -D 19|17|p|p|s|u|GP_Segment_3|GP_Segment_3|6005|None|/opt/greenplum/data2/primary/gpseg17|| -B 64
20190329:17:56:29:002460 gpsegstart.py_GP_Segment_3:gpadmin:GP_Segment_3:gpadmin-[CRITICAL]:-gpsegstart.py failed. (Reason='[Errno 12] Cannot allocate memory') exiting...
'
  stderr='''
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-DBID:19  FAILED  host:'GP_Segment_3' datadir:'/opt/greenplum/data2/primary/gpseg17' with reason:'cmd had rc=2 completed=True halted=False
  stdout='20190329:17:56:29:002460 gpsegstart.py_GP_Segment_3:gpadmin:GP_Segment_3:gpadmin-[INFO]:-Starting gpsegstart.py with args: -C en_US.utf8:en_US.utf8:en_US.utf8 -M mirrorless -V postgres (Greenplum Database) 5.16.0 build commit:23cec7df0406d69d6552a4bbb77035dba4d7dd44 -n 18 --era f9981c2cfd29d865_190329175627 -t 600 --master-checksum-version 1 -D 14|12|p|p|s|u|GP_Segment_3|GP_Segment_3|6000|None|/opt/greenplum/data/primary/gpseg12|| -D 15|13|p|p|s|u|GP_Segment_3|GP_Segment_3|6001|None|/opt/greenplum/data/primary/gpseg13|| -D 16|14|p|p|s|u|GP_Segment_3|GP_Segment_3|6002|None|/opt/greenplum/data/primary/gpseg14|| -D 17|15|p|p|s|u|GP_Segment_3|GP_Segment_3|6003|None|/opt/greenplum/data2/primary/gpseg15|| -D 18|16|p|p|s|u|GP_Segment_3|GP_Segment_3|6004|None|/opt/greenplum/data2/primary/gpseg16|| -D 19|17|p|p|s|u|GP_Segment_3|GP_Segment_3|6005|None|/opt/greenplum/data2/primary/gpseg17|| -B 64
20190329:17:56:29:002460 gpsegstart.py_GP_Segment_3:gpadmin:GP_Segment_3:gpadmin-[CRITICAL]:-gpsegstart.py failed. (Reason='[Errno 12] Cannot allocate memory') exiting...
'
  stderr='''
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-DBID:5  FAILED  host:'GP_Segment_1' datadir:'/opt/greenplum/data2/primary/gpseg3' with reason:'PG_CTL failed.'
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-DBID:3  FAILED  host:'GP_Segment_1' datadir:'/opt/greenplum/data/primary/gpseg1' with reason:'PG_CTL failed.'
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-DBID:10  FAILED  host:'GP_Segment_2' datadir:'/opt/greenplum/data/primary/gpseg8' with reason:'PG_CTL failed.'
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-DBID:11  FAILED  host:'GP_Segment_2' datadir:'/opt/greenplum/data2/primary/gpseg9' with reason:'PG_CTL failed.'
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-----------------------------------------------------


20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-----------------------------------------------------
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-   Successful segment starts                                            = 8
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[WARNING]:-Failed segment starts                                                = 10   <<<<<<<<
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-   Skipped segment starts (segments are marked down in configuration)   = 0
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-----------------------------------------------------
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-Successfully started 8 of 18 segment instances <<<<<<<<
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-----------------------------------------------------
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[WARNING]:-Segment instance startup failures reported
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[WARNING]:-Failed start 10 of 18 segment instances <<<<<<<<
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[WARNING]:-Review /home/gpadmin/gpAdminLogs/gpstart_20190329.log
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-----------------------------------------------------
20190329:18:06:32:002834 gpstart:GP_Master:gpadmin-[INFO]:-Commencing parallel segment instance shutdown, please wait...
..
20190329:18:06:34:002834 gpstart:GP_Master:gpadmin-[ERROR]:-gpstart error: Do not have enough valid segments to start the array.

# 解决方案
```
  减少每台主机的 segment 的数量。
```
